
version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    ports:
    - 5672:5672
  redis:
    image: redis:6
  worker:
    build:
      context: ..
      dockerfile: example/Dockerfile
  regular_client:
    build:
      context: ..
      dockerfile: example/Dockerfile
    command: python regular_celery.py
  async_client:
    build:
      context: ..
      dockerfile: example/Dockerfile
    command: python async_client.py
